notifications:
  irc: "chat.freenode.net#Heather"
  email: false
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
script:
  - make
after_script:
 - ./Mirana
